CREATE TYPE "public"."document_type" AS ENUM('text', 'diff', 'snippet');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "difflab_document_version" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"document_id" uuid NOT NULL,
	"content_inline" text,
	"storage_key" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "difflab_document" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"folder_id" uuid,
	"name" text NOT NULL,
	"type" "document_type" DEFAULT 'text' NOT NULL,
	"content_inline" text,
	"storage_key" text,
	"base_snapshot_id" uuid,
	"head_snapshot_id" uuid,
	"is_public" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "difflab_folder" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"name" text NOT NULL,
	"parent_id" uuid,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "difflab_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "difflab_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_document_version" ADD CONSTRAINT "difflab_document_version_document_id_difflab_document_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."difflab_document"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_document" ADD CONSTRAINT "difflab_document_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_document" ADD CONSTRAINT "difflab_document_folder_id_difflab_folder_id_fk" FOREIGN KEY ("folder_id") REFERENCES "public"."difflab_folder"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_document" ADD CONSTRAINT "difflab_document_base_snapshot_id_difflab_document_id_fk" FOREIGN KEY ("base_snapshot_id") REFERENCES "public"."difflab_document"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_document" ADD CONSTRAINT "difflab_document_head_snapshot_id_difflab_document_id_fk" FOREIGN KEY ("head_snapshot_id") REFERENCES "public"."difflab_document"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_folder" ADD CONSTRAINT "difflab_folder_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_folder" ADD CONSTRAINT "difflab_folder_parent_id_difflab_folder_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."difflab_folder"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "difflab_post" ADD CONSTRAINT "difflab_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "document_versions_document_idx" ON "difflab_document_version" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "documents_user_folder_idx" ON "difflab_document" USING btree ("user_id","folder_id");--> statement-breakpoint
CREATE INDEX "documents_public_idx" ON "difflab_document" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "documents_base_snapshot_idx" ON "difflab_document" USING btree ("base_snapshot_id");--> statement-breakpoint
CREATE INDEX "documents_head_snapshot_idx" ON "difflab_document" USING btree ("head_snapshot_id");--> statement-breakpoint
CREATE INDEX "folders_user_parent_idx" ON "difflab_folder" USING btree ("user_id","parent_id");--> statement-breakpoint
CREATE UNIQUE INDEX "folders_user_parent_name_idx" ON "difflab_folder" USING btree ("user_id","parent_id","name");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "difflab_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "difflab_post" USING btree ("name");